name: Deploy AI Agents System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm run test:simple
      env:
        CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        NODE_ENV: test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: |
        echo "Building AI Agents Team Management System..."
        mkdir -p dist
        cp -r agents dist/
        cp -r api_gateway dist/
        cp -r telegram_bot dist/
        cp -r knowledge_base dist/
        cp package.json dist/
        echo "Build completed!"
    
    # Можно добавить деплой на Heroku, Railway, Render и т.д.
    # Пример для Railway:
    # - name: Deploy to Railway
    #   uses: railway/railway@v2
    #   with:
    #     api-token: ${{ secrets.RAILWAY_TOKEN }}
    
    - name: Deploy notification
      run: |
        echo "🚀 Deployment completed!"
        echo "📍 API Gateway: Ready for deployment"
        echo "🤖 Telegram Bot: Ready for deployment"
        echo "🧠 AI Agents: Ready for deployment"